site_name: MS-Swift 笔记库
site_description: 个人的 ms-swift 学习与实践笔记，包含 SFT 训练、SwanLab 集成、Flash Attention 安装等
site_author: Your Name
site_url: https://yourusername.github.io/ms-swift-notebook

# 仓库信息
repo_name: ms-swift-notebook
repo_url: https://github.com/yourusername/ms-swift-notebook
edit_uri: edit/main/

# 文档目录
docs_dir: docs

# 主题配置
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# 导航结构
nav:
  - 首页: index.md
  - 快速开始:
    - 简介: notes/00-简介.md
    - 环境与升级: notes/10-环境与工具.md
  - 训练指南:
    - 数据与SFT训练: notes/20-数据与SFT训练.md
    - Flash Attention 安装: notes/50-FlashAttention安装.md
    - SwanLab 集成: notes/30-SwanLab集成.md
  - 推理测试:
    - 推理测试与问题解决: notes/60-推理测试与问题解决.md
  - 模型评测:
    - 模型评测与心理学基准: notes/70-模型评测与心理学基准.md
  - 问题解决:
    - 网络代理问题解决: notes/80-网络代理问题解决.md
  - 实验报告:
    - mh-sharegpt SFT: notes/40-实验报告-mh-sharegpt-sft.md
  - 配置参考:
    - 密钥与数据索引: notes/90-密钥与数据索引.md

# 插件配置
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            show_source: true

# 额外配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/ms-swift-notebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

# 版权信息
copyright: Copyright &copy; 2025 Your Name

# Google Analytics（可选，需要时取消注释并填入真实 ID）
# extra_analytics:
#   provider: google
#   property: G-XXXXXXXXXX
